Use the gocheck binary to run Postgres matrix tests.

diff --git a/tests/test-smoke b/tests/test-smoke
--- a/tests/test-smoke
+++ b/tests/test-smoke
@@ -11,8 +11,9 @@ DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
 # Read the absolute path to the exporter
 postgres_exporter=$(readlink -f $1)
+test_binary=$(readlink -f $2)
 exporter_port=9187
-$exporter_port=password
+exporter_password=password
 
 cd $DIR
 
@@ -25,6 +26,35 @@ VERSIONS=( \
     9.6 \
 )
 
+wait_for_postgres() {
+    local CONTAINER_NAME=$1
+    if [ -z $CONTAINER_NAME ]; then
+        echo "No container name specified." 1>&2
+        exit 1
+    fi
+    local WAIT_START=$(date +%s)
+    echo "Waiting for postgres to start..."
+    while ! docker exec $CONTAINER_NAME bash -c "psql -U postgres -c \"select 'running'\" > /dev/null 2>&1 " ; do
+        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
+            echo "Timed out waiting for postgres!" 1>&2
+            exit 1
+        fi
+        sleep 1
+    done    
+}
+
+wait_for_exporter() {
+    local DAEMON_WAIT_START=$(date +%s)
+    echo "Waiting for exporter to start..."
+    while ! nc -z localhost $exporter_port ; do
+        if [ $(( $(date +%s) - $DAEMON_WAIT_START )) -gt $TIMEOUT ]; then
+            echo "Timed out waiting for exporter!" 1>&2
+            exit 1            
+        fi
+        sleep 1
+    done
+}
+
 smoketest_postgres() {
     local version=$1
     local CONTAINER_NAME=postgres_exporter-test-smoke
@@ -35,40 +65,22 @@ smoketest_postgres() {
     
     echo "Test standalone cluster..."
     CONTAINER_NAME=$(docker run -d -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -p 127.0.0.1:55432:5432 $CUR_IMAGE)
-
     trap "docker logs $CONTAINER_NAME ; docker kill $CONTAINER_NAME ; docker rm $CONTAINER_NAME; exit 1" EXIT INT TERM
+    wait_for_postgres $CONTAINER_NAME
 
-    local WAIT_START=$(date +%s)
-    while ! docker exec $CONTAINER_NAME bash -c "psql -U postgres -c \"select 'running'\" > /dev/null 2>&1 " ; do
-        echo "Waiting for postgres to start..."
-        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
-            echo "Timed out waiting for postgres!" 1>&2
-            exit 1
-        fi
-        sleep 1
-    done
-
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@localhost:55432/?sslmode=disable" $postgres_exporter &
-    exporter_pid=$!
-    trap "docker logs $CONTAINER_NAME ; docker kill $CONTAINER_NAME ; docker rm $CONTAINER_NAME ; kill $exporter_pid; exit 1" EXIT INT TERM
-    local DAEMON_WAIT_START=$(date +%s)
-    while ! nc -z localhost $exporter_port ; do
-        echo "Waiting for exporter to start..."
-        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
-            echo "Timed out waiting for exporter!" 1>&2
-            exit 1            
-        fi
-        sleep 1
-    done
-
-    wget -q -O - http://localhost:$exporter_port/metrics 1> /dev/null
-    if [ "$?" != "0" ]; then
-        echo "Failed on postgres $version ($DOCKER_IMAGE)" 1>&2
-        kill $exporter_pid
-        exit 1
-    fi
-
-    kill $exporter_pid
+    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@localhost:55432/?sslmode=disable" $test_binary || exit $?
+#    exporter_pid=$!
+#    trap "docker logs $CONTAINER_NAME ; docker kill $CONTAINER_NAME ; docker rm $CONTAINER_NAME ; kill $exporter_pid; exit 1" EXIT INT TERM
+#    wait_for_exporter
+#
+#    wget -q -O - http://localhost:$exporter_port/metrics 1> /dev/null
+#    if [ "$?" != "0" ]; then
+#        echo "Failed on postgres $version ($DOCKER_IMAGE)" 1>&2
+#        kill $exporter_pid
+#        exit 1
+#    fi
+#
+#    kill $exporter_pid
     docker kill $CONTAINER_NAME
     docker rm $CONTAINER_NAME
     trap - EXIT INT TERM
@@ -88,47 +100,21 @@ smoketest_postgres() {
     master_container=$(docker-compose ps -q pg-master)
     slave_container=$(docker-compose ps -q pg-slave)
     master_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $master_container)
-
-    local WAIT_START=$(date +%s)
-    while ! docker exec $master_container bash -c "psql -U postgres -c \"select 'running'\" > /dev/null 2>&1 " ; do
-        echo "Waiting for postgres master to start..."
-        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
-            echo "Timed out waiting for postgres!" 1>&2
-            exit 1
-        fi
-        sleep 1
-    done
+    wait_for_postgres $master_container
+    wait_for_postgres $slave_container
     
-    local WAIT_START=$(date +%s)
-    while ! docker exec $slave_container bash -c "psql -U postgres -c \"select 'running'\" > /dev/null 2>&1 " ; do
-        echo "Waiting for postgres master to start..."
-        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
-            echo "Timed out waiting for postgres!" 1>&2
-            exit 1
-        fi
-        sleep 1
-    done
-    
-    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $postgres_exporter &
-    exporter_pid=$!
-    trap "docker-compose logs; docker-compose down ; docker-compose rm -v ; kill $exporter_pid; exit 1" EXIT INT TERM
-    local DAEMON_WAIT_START=$(date +%s)
-    while ! nc -z localhost $exporter_port ; do
-        echo "Waiting for exporter to start..."
-        if [ $(( $(date +%s) - $WAIT_START )) -gt $TIMEOUT ]; then
-            echo "Timed out waiting for exporter!" 1>&2
-            exit 1            
-        fi
-        sleep 1
-    done
+    DATA_SOURCE_NAME="postgresql://postgres:$POSTGRES_PASSWORD@$master_ip:5432/?sslmode=disable" $test_binary || exit $?
+#    exporter_pid=$!
+#    trap "docker-compose logs; docker-compose down ; docker-compose rm -v ; kill $exporter_pid; exit 1" EXIT INT TERM
+#    wait_for_exporter
 
-    wget -q -O - http://localhost:$exporter_port/metrics 1> /dev/null
-    if [ "$?" != "0" ]; then
-        echo "Failed on postgres $version ($DOCKER_IMAGE)" 1>&2
-        exit 1
-    fi
-
-    kill $exporter_pid
+#    wget -q -O - http://localhost:$exporter_port/metrics 1> /dev/null
+#    if [ "$?" != "0" ]; then
+#        echo "Failed on postgres $version ($DOCKER_IMAGE)" 1>&2
+#        exit 1
+#    fi
+#
+#    kill $exporter_pid
     
     docker-compose down
     docker-compose rm -v
